### ISSUE TITLE
Timestamps on "history" and "Messages" are incorrect

### ISSUE THREAD

**Issue by Biff49** [efmer/boinctasks-js#78]
Hi Stephen,

It seems the locale detection is off.
That would certainly explain the problem 
Might have to add a manual override
Right now I am on vacation in Canada, not much I can do for some time.

You can raise an issue in GitHub in case I forget 

Kind regards, met vriendelijke groeten

Fred
=========================================================================================

Really like your new JS version, I have already uninstalled BoincTasks which was running in Wine on my Linux Mint desktop.   But, the timestamps on the history (you need to change that to "History") and Messages tabs are wrong.

I am in Canada, Eastern Daylight time zone (EDT):

stephen@Lubbert1:~$ date
Mon Sep 13 23:36:56 EDT 2021
stephen@Lubbert1:~$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
stephen@Lubbert1:~$ 

But when I click Help/About in BoincTasks-JS at the bottom of the screen it shows "Locale: en-GB", I assume that is Great Britain, but in any case, is not CAnada.   Does this explain the timestamps being wrong?  Is this a problem with the software?  Or do I need to set something on my end?

Stephen Tent

**Comment by efmer** [comment]
Time was incorrectly converted to local time. Fixed in V 1.15

**Comment by Biff49** [comment]
Hi Fred,

I am running version 1.23.     Are you telling me that the problem is with
something on my end?

I see there is a version 1.24 on GitHub, I'll install that this morning.

.

**Comment by Biff49** [comment]
I see now that 1.23 is the latest version so I will stay with that.

.

**Comment by efmer** [comment]
The problem is in all versions and I'm testing V 1.25 that fixes it.

<Help/About in BoincTasks-JS at the bottom of the screen it shows "Locale: en-GB".>
Windows Time & Languages Windows display language is probably set to English (United Kingdom)

**Comment by efmer** [comment]
Fixed 1.27

**Comment by Biff49** [comment]
1.27 installed; timestamps (even the historical ones) look correct now.
But Help/About still shows the locale as en-GB, but with Region=CA.

Thanks

Stephen

.

**Comment by efmer** [comment]
On my computer the default in English is British.
That gives en-GB.
The region probably gives CA.

Possible settings https://source.chromium.org/chromium/chromium/src/+/master:ui/base/l10n/l10n_util.cc

You can override
BoincTasks Settings -> Region put in en-CA or fr-CA and press Apply.
This only applies to the date format, that will probably not change at all except when you change it into fr-CA.
